### ISSUE TITLE
Feature request - Add option to not include Azure China files and parameters.

### ISSUE THREAD

**Issue by kardiojack** [Azure/ALZ-PowerShell-Module#112]
### Is your feature request related to a problem? Please describe.
I have no plans of ever deploying products in China. It is frustrating that the Bicep accelerator is cluttered with so many files and options I will never use.

### Describe the solution you'd like
An opt-in feature flag during accelerator setup that lets users indicate that they do not want Azure China files and options in their accelerator.

### Describe alternatives you've considered
Manually deleting all files and references before committing to git. Prone to error and hard to upgrade.

### Additional context
None.

**Comment by oZakari** [comment]
Hi @kardiojack, thanks for bringing this up as I also believe this is something that would be improved as well. Currently, we are pulling down the entire ALZ-Bicep release version which is why you're seeing the Azure China parameter files.

We could use an approach to remove the Microsoft China parameter files based upon the region a user selects. Would you also see benefit to only pulling down the Bicep modules as in everything `infra-as-code\bicep`? What would be your ideal scenario beyond just removing the Azure China references?

**Comment by jaredfholgate** [comment]
The latest version of the accelerator no longer pushes the `infra-as-code` folder to source control, it pulls it down on demand as part of the CI / CD process instead. Therefore this may no longer be an issue.
