### ISSUE TITLE
Can the test-ALZRequirement -IaC "bicep" command check if AZ CLI Bicep is installed?

### ISSUE THREAD

**Issue by jamiepla1** [Azure/ALZ-PowerShell-Module#90]
I am using Bicep included with AZ CLI.

When running test-ALZRequirement -IaC "bicep" it fails with

Test-ALZRequirement: Bicep is not installed. Please install Bicep.

I did install Bicep using winget and the error went away, but the AZ CLI Bicep is working fine.

**Comment by oZakari** [comment]
Hi @jamiepla1, the test itself is just running Get-Command -Name Bicep. Since Azure CLI just installs an embedded version of Bicep, it doesn't add it to the path. 

Because all of our documentation and scripts are utilizing Azure PowerShell, we want people to install Bicep manually as PowerShell cannot take advantage of the embedded version of Bicep within the Azure CLI. I will update the failed test output to be more specific though.

**Comment by jaredfholgate** [comment]
@jamiepla1 the latest version of the accelerator automates Bicep bootstrapping, so I will close this for now. Please re-open if it is still an issue though.
